// <auto-generated />
using BookLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623175348_AddIsbnToBook")]
    partial class AddIsbnToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookLibrary.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "J.R.R. Tolkien"
                        });
                });

            modelBuilder.Entity("BookLibrary.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 328,
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 112,
                            Title = "Animal Farm",
                            Year = 1945
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 232,
                            Title = "Homage to Catalonia",
                            Year = 1938
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 432,
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 474,
                            Title = "Emma",
                            Year = 1815
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 310,
                            Title = "The Hobbit",
                            Year = 1937
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 423,
                            Title = "The Fellowship of the Ring",
                            Year = 1954
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 352,
                            Title = "The Two Towers",
                            Year = 1954
                        });
                });

            modelBuilder.Entity("BookLibrary.Entities.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 4
                        },
                        new
                        {
                            BookId = 6,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 7,
                            TagId = 2
                        });
                });

            modelBuilder.Entity("BookLibrary.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Political"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        });
                });

            modelBuilder.Entity("BookLibrary.Entities.Book", b =>
                {
                    b.HasOne("BookLibrary.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookLibrary.Entities.BookTag", b =>
                {
                    b.HasOne("BookLibrary.Entities.Book", null)
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibrary.Entities.Tag", null)
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookLibrary.Entities.Book", b =>
                {
                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("BookLibrary.Entities.Tag", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
